MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog.views import PostListView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',PostListView.as_view(),name='post_list'),
    re_path(r'blog/',include('blog.urls',namespace='blog')),
    re_path(r'accounts/',include('accounts.urls',namespace='accounts')),
]

MyBlog/accounts/urls.py
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from . import views
from django_otp.forms import OTPAuthenticationForm
from django.urls import reverse_lazy

app_name='accounts'
urlpatterns = [
        #re_path(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),

        re_path(r'^login/$',views.user_login,name='login'),


        re_path(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
        re_path(r'^signup/$',views.SignUp.as_view(),name='signup'),
        re_path(r'^change-password/$',views.CustomPasswordChangeView.as_view(),name='change-password'),
        re_path(r'^password_reset/$',views.CustomPasswordResetView.as_view(),name='password_reset'),
        re_path(r'^password_reset/done/$',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name='password_reset_done'),
        re_path(r'^reset/<uidb64>/<token>/$',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),
        re_path('^reset/done/$',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html') ,name='password_reset_complete'),
        re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
        ]

MyBlog/blog/urls.py
from django.urls import path,re_path
from blog import views

app_name ='blog'
urlpatterns = [
            re_path(r'^about/$',views.AboutView.as_view(),name="about"),
            #re_path(r'^$',views.PostListView.as_view(),name="post_list"),
            re_path(r'^post/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='post_detail'),
            re_path(r'^post/new/$',views.CreatePostView.as_view(),name="post_new"),
            re_path(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name="post_edit"),
            re_path(r'^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name="post_remove"),
            re_path(r'^drafts/(?P<email>[-\w.@+]+)/$',views.draftListView,name="post_draft_list"),
            re_path(r'^alluserpost/(?P<email>[-\w.@+]+)/$',views.alluserpost,name="alluserpost"),
            re_path(r'^post/(?P<pk>\d+)/comment/$',views.add_comments_to_post,name="add_comments_to_post"),
            re_path(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name="comment_approve"),
            re_path(r'^comment/(?P<pk>\d+)/$',views.comment_remove,name='comment_remove'),
            re_path(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name="post_publish"),

]

MyBlog/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class User(AbstractUser):
    username=models.CharField(blank=False,unique=True,max_length=256)
    email = models.EmailField(unique=True)
    email_confirmed = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'

    #USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username',]

    def __str__(self):
        return self.email

MyBlog/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

class UserCreateForm(UserCreationForm):

    class Meta():
        fields =('username','email',)
        model=get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['email'].label = 'Email Address'

class UserLoginForm(forms.Form):
    email=forms.EmailField(label="enter the email:")
    password=forms.CharField(widget=forms.PasswordInput,label="enter password")

MyBlog/accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView
from django.contrib.auth.views import (PasswordChangeView,
                                PasswordResetView,
                                LoginView
                                )
from . import forms
from django.contrib.auth.forms import (PasswordChangeForm,
                            PasswordResetForm,
                            )

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.http import HttpResponse ,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout


from .models import User



# Create your views here.

def user_login(request):
    if request.method=='POST':
        email=request.POST.get('email')
        password=request.POST.get('password')

        try:
            print("trying to authenticate")
            user=authenticate(email=email,password=password)
            print(user)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    HttpResponse("account is not active...")
            else:
                try:
                    user=User.objects.get(email=email)
                    if user.email_confirmed:
                        return HttpResponse("Incorrect password")
                    else:
                        current_site=get_current_site(request)
                        message = render_to_string('accounts/account_activate_message.html', {
                                'user':user,
                                'domain':current_site.domain,
                                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                                'token': account_activation_token.make_token(user),
                            })
                        mail_subject = 'Activate your blog account.'
                        to_email = email
                        email_m = EmailMessage(mail_subject, message, to=[to_email])
                        email_m.send()
                        return HttpResponse("Email is not confirmed! Please Confirm")


                except:
                    return HttpResponse("Please sign Up!")
        except:
            return HttpResponse("Account is not registered ")
    else:
        print("in views")
        form=forms.UserLoginForm()
        return render(request,'accounts/login.html',{'form':form})




class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url=reverse_lazy('accounts:login')
    template_name='accounts/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            print("hello1")
            return self.form_valid(form,request)
        else:
            print("form invlaid")
            try:
                User.objects.get(email=request.POST['email'])
                return HttpResponse("Email is already registered")
            except:
                return HttpResponse("Password doesn't match")

    def form_valid(self,form,request):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        print('hello2')
        current_site=get_current_site(request)
        message = render_to_string('accounts/account_activate_message.html', {
                'user':self.object,
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).decode(),
                'token': account_activation_token.make_token(self.object),
            })
        mail_subject = 'Activate your blog account.'
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.send()
        return super().form_valid(form)



    """def form_valid(self,request,form):
        self.object = form.save()
        #self.object.is_active = False
        #self.object = self.object.save()
        current_site=get_current_site(request)
        message = render_to_string('accounts/account_activate_message.html', {
                'user':self.object,
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)),
                'token': account_activation_token.make_token(self.object),
            })
        mail_subject = 'Activate your blog account.'
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.send()
        #return HttpResponse('Please confirm your email address to complete the registration')
        return super().form_valid(form)"""

class CustomPasswordChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('post_list')
    template_name = 'accounts/password_change.html'

class CustomPasswordResetView(PasswordResetView):
    form_class = PasswordResetForm
    template_name = 'accounts/password_reset_form.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    email_template_name = 'accounts/password_reset_email.html'

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed=True
        user.save()
        return redirect('accounts:logout')
    else:
        return HttpResponse('Activation link is invalid!')

MyBlog/accounts/templates/accounts/account_activate_message.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

MyBlog/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Login Page</title>
  </head>
  <body>
    <div class="jumbotron">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Login">
      </form>
    </div>

  </body>
</html>

MyBlog/accounts/templates/accounts/password_change.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Password Change Form</title>
  </head>
  <body>
    <div class="jumbotron">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Change">
      </form>
    </div>

  </body>
</html>

MyBlog/accounts/templates/accounts/password_reset_complete.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'post_list' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

MyBlog/accounts/templates/accounts/password_reset_confirm.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'post_list' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset confirmation' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

{% if validlink %}

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% trans 'New password:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="{% trans 'Change my password' %}">
</fieldset>
</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

MyBlog/accounts/templates/accounts/password_reset_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'post_list' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

MyBlog/accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}custom: You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

MyBlog/accounts/templates/accounts/password_reset_form.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'post_list' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">
        {{ form.email.errors }}
        <label for="id_email">{% trans 'Email address:' %}</label>
        {{ form.email }}
    </div>
    <input type="submit" value="{% trans 'Reset my password' %}">
</fieldset>
</form>

{% endblock %}

MyBlog/accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SignUp</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron">
      <form  method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Sign Up">
      </form>

    </div>


  </body>
</html>