MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog.views import PostListView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',PostListView.as_view(),name='post_list'),
    re_path(r'blog/',include('blog.urls',namespace='blog')),
    re_path(r'accounts/',include('accounts.urls',namespace='accounts')),
]

MyBlog/accounts/urls.py
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from . import views
from django_otp.forms import OTPAuthenticationForm
from django.urls import reverse_lazy

app_name='accounts'
urlpatterns = [
        #re_path(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),

        re_path(r'^login/$',views.user_login,name='login'),


        re_path(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
        re_path(r'^signup/$',views.SignUp.as_view(),name='signup'),
        re_path(r'^change-password/$',views.CustomPasswordChangeView.as_view(),name='change-password'),
        re_path(r'^password_reset/$',views.CustomPasswordResetView.as_view(),name='password_reset'),
        re_path(r'^password_reset/done/$',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name='password_reset_done'),
        re_path(r'^reset/<uidb64>/<token>/$',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),
        re_path('^reset/done/$',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html') ,name='password_reset_complete'),
        re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
        ]

MyBlog/blog/urls.py
from django.urls import path,re_path
from blog import views

app_name ='blog'
urlpatterns = [
            re_path(r'^about/$',views.AboutView.as_view(),name="about"),
            #re_path(r'^$',views.PostListView.as_view(),name="post_list"),
            re_path(r'^post/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='post_detail'),
            re_path(r'^post/new/$',views.CreatePostView.as_view(),name="post_new"),
            re_path(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name="post_edit"),
            re_path(r'^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name="post_remove"),
            re_path(r'^drafts/(?P<email>[-\w.@+]+)/$',views.draftListView,name="post_draft_list"),
            re_path(r'^alluserpost/(?P<email>[-\w.@+]+)/$',views.alluserpost,name="alluserpost"),
            re_path(r'^post/(?P<pk>\d+)/comment/$',views.add_comments_to_post,name="add_comments_to_post"),
            re_path(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name="comment_approve"),
            re_path(r'^comment/(?P<pk>\d+)/$',views.comment_remove,name='comment_remove'),
            re_path(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name="post_publish"),

]

MyBlog/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from accounts.models import User


# Create your models here.
class Post(models.Model):
    author=models.ForeignKey('accounts.User',null =True, on_delete=models.SET_NULL)
    title=models.CharField(max_length=256)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now())
    published_date=models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey('blog.post',related_name='comments',on_delete=models.CASCADE)
    author=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now())
    approved_comment=models.BooleanField(default=False)

    def approve(self):
        self.approved_comment=True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

MyBlog/blog/forms.py
from django import forms
from blog.models import Post,Comment
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

    class Meta():
        model=Post
        fields=('title','text')

        widgets={
        'title':forms.TextInput(attrs={'class':'textinputclass'}),
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model=Comment
        fields=('text',)

        widgets={
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')

MyBlog/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import(DeleteView,UpdateView,TemplateView,CreateView,ListView,DetailView)
from blog.models import Comment,Post
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import CommentForm,PostForm,UserForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
# Create your views here.

class AboutView(TemplateView):
    template_name='blog/about.html'

class PostListView(ListView):
    model=Post
    template_name='blog/post_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()) #.order_by('-published_date')

class PostDetailView(DetailView):
    model=Post
    template_name='blog/post_detail.html'



class CreatePostView(LoginRequiredMixin,CreateView):
    login_url='/login/'
    model=Post
    redirect_field_name='blog/post_detail.html'

    form_class=PostForm

    def form_valid(self,form):
        self.object =form.save(commit=False)
        self.object.author=self.request.user
        self.object.save()
        return super().form_valid(form)







class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    model=Post
    #redirect_field_name='blog/post_detail.html'
    form_class=PostForm

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model=Post
    success_url=reverse_lazy('post_list')

"""class DraftListView(LoginRequiredMixin,ListView):
    login_url='/login/'
    redirect_field_name='block/post_draft_list.html'
    model=Post

    #def get_queryset(self):
        #return Post.objects.filter(published_date__lte=timezone.now())
"""
@login_required
def alluserpost(request,*args,**kwargs):
    email=kwargs['email']
    values=Post.objects.filter(author__email__exact = email,published_date__isnull=True)

    return render(request,'blog/post_draft_list.html',{'posts':values})

@login_required
def draftListView(request,*args,**kwargs):
    email=kwargs['email']
    values=Post.objects.filter(author__email__exact = email,published_date__lte=timezone.now())
    return render(request,'blog/post_draft_list.html',{'posts':values})





##################################################
##################################################
@login_required
def add_comments_to_post(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.post=post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
        else:
            form=CommentForm()
        return render(request,'blog/comment_form.html',{'form':form})
    else:
        form=CommentForm()
        return render(request,'blog/comment_form.html',{'form':form})


@login_required
def comment_approve(request,pk):
    comment=get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment=get_object_or_404(Comment,pk=pk)
    post_pk=comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)

@login_required
def post_publish(request,pk):
    post=get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)

"""
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('post_list'))

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('post_list'))

            else:
                HttpResponse("account is not active")
        else:
            return HttpResponse("Invalid login")
    else:
        return render(request,'registration/login.html',{})

def user_register(request):
    registered=False

    if request.method=='POST':

        user_form=UserForm(data=request.POST)

        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            registered=True

            return HttpResponseRedirect(reverse('post_list'))

        else:
            print(user_form.errors)
    else:
        user_form=UserForm()
        return render(request,'registration/register.html',{'user_form':user_form})

        """

MyBlog/blog/templates/blog/about.html
{%extends "blog/base.html" %}
{% block content %}


<h1>Hello welcome to my block!</h1>
<h1>Please Register</h1>
{% endblock %}

MyBlog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates|Russo+One" rel="stylesheet">
    <title></title>
  </head>
  <body class="loader">
    <nav class="navbar navbar-expand-lg navbar-light  navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'post_list' %}">My Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'blog:about' %}">About <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="https://github.com/">Github</a>
      <a class="nav-item nav-link" href="http://gmail.com">Gmail</a>

      {% if user.is_authenticated %}
      <a class="nav-item nav-link" href="{% url 'blog:post_new' %}"> New Post</a>
      <a class="nav-item nav-link" href="{% url 'blog:post_draft_list' email=user.email %}">All</a>
      <a class="nav-item nav-link" href="{% url 'blog:alluserpost' email=user.email %}">Drafts</a>
      <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      <a class="nav-item nav-link" >Welcome: {{user.username}}</a>
       {% else %}
      <a class=" nav-item nav-link" href="{% url 'accounts:login' %}">  login<span class='glyphicon glyphicon-user'></span></a>
      <a class="nav-item nav-link" href="{% url 'accounts:signup' %}"> Register<span class='glyphicon glyphicon-user'></span></a>
        {% endif %}
    </div>
  </div>
</nav>

<div class="content container">
  <div class="jumbotron">
    {% block content %}
    {% endblock %}
  </div>

</div>
  </body>
</html>

MyBlog/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block content %}

<h1>New Comment</h1>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Post Comment</button>
</form>
<script>
  var editor = new MediumEditor('.editable');

</script>
{% endblock %}

MyBlog/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}

{% if user.email == post.author.email %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{object}}</p>
  <input type="submit" class="btn btn-danger"  value="Confirm">
</form>
{% else %}
<p>access deneid</p>
{% endif %}
{% endblock %}

MyBlog/blog/templates/blog/post_detail.html
{%extends "blog/base.html" %}
{% block content %}
<h1 class="posttitle loader">{{post.title}}</h1>

{% if post.published_date %}
<div class="date postdate">
{{post.published_date}}
</div>
{% endif%}
<p class="postcontent">{{post.title|safe|linebreaksbr}}</p>
<p class="postcontent">{{post.text|safe|linebreaksbr}}</p>

<p>{% if post.author.username %}</p>
{{post.author.username}}
{% else %}
<p>Anonymous</p>
{% endif %}

{% if user.is_authenticated %}

      {% if user.email == post.author.email %}
      <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">Edit</a>
          {% if post.published_date is null %}
              <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
          {% else %}
              <p>Published on: {{ post.published_date }}</p>
          {% endif %}
      <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">Remove</a>
      {% endif %}
      <hr>
      <a class="btn btn-primary" href="{% url 'blog:add_comments_to_post' pk=post.pk %}">Add comments</a>
      <div class="continer">

      {% for comment in post.comments.all %}

        <br>
          {% if comment.approved_comment %}
            {{comment.created_date}}

                {% if user.email == comment.author or user.email == post.author.email %}
                  <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}">Remove1</a>
                {% endif %}

          <p>{{comment.text|safe|linebreaksbr}}</p>
          <p>Posted by: {{comment.author}}</p>

          {% else %}

          {{comment.created_date}}

              {% if user.email == post.author.email %}
              <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">Approve</a>
              {% endif %}

              {% if user.email == comment.author or user.email == post.author.email %}
                <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}">Remove1</a>
              {% endif %}

        <p>{{comment.text|safe|linebreaksbr}}</p>
        <p>Posted by: {{comment.author}}</p>
          {%endif%}

          {% empty %}
          <p>No comments</p>
        {% endfor %}

      </div>
{% endif%}

{% endblock %}

MyBlog/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}

{% block content %}

<div class="post">
  {% for post in posts %}
  <p class="date" >Created : {{post.created_date|date:'d-m-y'}}</p>
  <h1 >  <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h1>
  <p>{{post.text|safe}}</p>
  <p>Published date: {{post.published_date}}</p>
  <hr>
  {% endfor %}
</div>

{% endblock %}

MyBlog/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
<h1>New Post</h1>
<form class="post-form"  method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Save</button>
</form>

<script>
  var editor = new MediumEditor('.editable');
</script>

{% endblock %}

MyBlog/blog/templates/blog/post_list.html
{%extends "blog/base.html" %}
{% block content %}
<div class="centerstage">
  {% for post in post_list %}
  <div class="post">
    <h1> <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h1>
    <div class="date">
      <p>Published on: {{post.published_date}}</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'blog:post_detail' pk=post.pk %}">Click here for Comments</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">Click here for Comments</a>
    {% endif %}


  </div>
  {% endfor %}

</div>
{% endblock %}